--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    user_id bigint NOT NULL,
    created timestamp without time zone,
    email character varying(255),
    enabled boolean NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user_roles (
    app_user_user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.app_user_roles OWNER TO postgres;

--
-- Name: app_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- Name: member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member (
    member_id bigint NOT NULL,
    created timestamp without time zone,
    email character varying(255),
    enabled boolean NOT NULL,
    member_name character varying(255),
    password character varying(255)
);


ALTER TABLE public.member OWNER TO postgres;

--
-- Name: member_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_roles (
    member_member_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.member_roles OWNER TO postgres;

--
-- Name: post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post (
    post_id bigint NOT NULL,
    created_date timestamp without time zone,
    description character varying(255),
    post_name character varying(255),
    user_id bigint
);


ALTER TABLE public.post OWNER TO postgres;

--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_date timestamp without time zone,
    token character varying(255)
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(20)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (user_id, created, email, enabled, password, username) FROM stdin;
1	2022-01-18 14:13:34.322047	first@abcdef.com	t	$2a$10$CRFr8i1VHahMv8WeOwktBe4WeJ6Fc9KcvpZBiOGu4kcxBbcJVv.bq	first
2	2022-01-19 08:59:03.838699	second@aaa.com	t	$2a$10$olHNJV9Q5/SlUEhLRTvU6.43/QrI8B3yihB6dVz2QIGDEiObocgxO	second
3	2022-01-19 10:30:08.073126	third@aaa.com	t	$2a$10$vhphIpcR1qd2OEZuyK4E9.4na6cgzcLyuPpkn2riSQFyUvQh28NmG	third
4	2022-01-19 10:37:11.615688	fourth@aaa.com	t	$2a$10$rvj7OdbiNLOrmGMPSDxSseCQDgezX2zDvVfXawDXxTmUlNNb0r4.u	fourth
\.


--
-- Data for Name: app_user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user_roles (app_user_user_id, role_id) FROM stdin;
1	1
2	1
3	1
4	1
\.


--
-- Data for Name: member; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.member (member_id, created, email, enabled, member_name, password) FROM stdin;
\.


--
-- Data for Name: member_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.member_roles (member_member_id, role_id) FROM stdin;
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.post (post_id, created_date, description, post_name, user_id) FROM stdin;
10	2022-01-19 16:48:28.07687	eee	eee	2
16	2022-01-20 08:42:15.90749	kkk	kkk	2
\.


--
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_token (id, created_date, token) FROM stdin;
2	2022-01-18 16:29:43.447515	3360f342-b6ce-40cc-8ffd-53fb60d0af56
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name) FROM stdin;
1	ROLE_USER
2	ROLE_ADMIN
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_user_id, role_id) FROM stdin;
\.


--
-- Name: app_user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_user_id_seq', 4, true);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 17, true);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 12, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 2, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);


--
-- Name: app_user_roles app_user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT app_user_roles_pkey PRIMARY KEY (app_user_user_id, role_id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (member_id);


--
-- Name: member_roles member_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_roles
    ADD CONSTRAINT member_roles_pkey PRIMARY KEY (member_member_id, role_id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (post_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_user_id, role_id);


--
-- Name: post fk4p1xhm755mme4ykg5am4ati4r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk4p1xhm755mme4ykg5am4ati4r FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: app_user_roles fk7j68xnb7cl41m3b1leb0b186g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT fk7j68xnb7cl41m3b1leb0b186g FOREIGN KEY (app_user_user_id) REFERENCES public.app_user(user_id);


--
-- Name: app_user_roles fkkxwhjke5g0yvja54osexos75t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT fkkxwhjke5g0yvja54osexos75t FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: member_roles fkruptm2dtwl95mfks4bnhv828k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_roles
    ADD CONSTRAINT fkruptm2dtwl95mfks4bnhv828k FOREIGN KEY (member_member_id) REFERENCES public.member(member_id);


--
-- PostgreSQL database dump complete
--
