version : "3.7"
services:
    # db:
    #     container_name: spring-db
    #     image: postgres:12.9
    #     environment:
    #         POSTGRES_DB: demo
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: admin
    #     volumes:
    #         - ./data:/var/lib/postgresql/data
    #     ports:
    #         - "5432:5432"
    #     restart: always
    app:
        container_name: spring-app
        image: openjdk:11-jdk
        ports:
            - "8080:8080"
        volumes:
            - ./spring-template:/spring-template
        working_dir: /spring-template
        command: ["./gradlew", "bootrun"]
        # depends_on:
        #     - db
        # restart: always